name: deposits_oneclick_checkout
description: A package to enable customers pay for purchased items on a one click-checkout button.
version: 0.0.3
homepage: https://github.com/DepositsTeam/deposits-oneclick-checkout

false_secrets:
  - /lib/app/modules/linked/linked/linked.dart
  - /lib/app/modules/google_search/places_service.dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #for state management
  get: ^4.6.1
  get_storage: ^2.0.3
  #for google fonts
  google_fonts: ^2.3.1
  #for spink kit loaders
  flutter_spinkit: ^5.1.0
  #for loading svgs
  flutter_svg: ^1.0.3
  #for http calls
  dio: ^4.0.4
  intl: ^0.17.0
  another_flushbar: ^1.10.28
  webview_flutter: ^3.0.1
  url_launcher: ^6.0.20
  http: ^0.13.4
  uuid: ^3.0.6
  flutter_dotenv: ^5.0.2
  path: ^1.7.0
  fpjs_pro_plugin: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - lib/app/common/assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
